# Generated by Django 2.0.4 on 2018-04-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(default='files/profile_pictures/default.jpg', upload_to='files/profile_pictures/')),
                ('IsAdmin', models.BooleanField(default=False)),
                ('IsVip', models.BooleanField(default=False)),
                ('VipExpiry', models.DateField(null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
