version: '3'

services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=dixit
      - POSTGRES_PASSWORD=qwe123

  redis:
    image: redis

  dixit:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DIXIT_DB_HOST=postgres
      - DIXIT_REDIS_HOST=redis
    volumes:
      - .:/usr/local/dixit
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
