version: '3'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=dixit
      - POSTGRES_PASSWORD=qwe123

  redis:
    image: redis
    restart: always

  server:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DIXIT_DB_HOST=db
      - DIXIT_REDIS_HOST=redis
    volumes:
      - .:/opt/dixit
      - /opt/dixit/node_modules
    ports:
      - "8000:8000"
    command: bash -c "npm run build
             && python manage.py collectstatic --noinput
             && ./wait-for-it.sh db:5432
             && python manage.py migrate
             && python manage.py runserver 0.0.0.0:8000"
