# Generated by Django 2.0.5 on 2018-06-13 15:13
from django.core.management import call_command
from django.db import migrations


def load_initial_data(apps, schema_editor):
    call_command('loaddata', 'initial_data')


class Migration(migrations.Migration):

    dependencies = [
        ('dixit', '0002_auto_20180608_0726'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
